export const ActionConstants = {
	LOADING:"LOADING",
	STOP_LOADING:"STOP_LOADING",
	REGISTER_SUCCESS:"REGISTER_SUCCESS",
	REGISTER_FAILED:"REGISTER_FAILED",
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	LOGIN_FAILED:"LOGIN_FAILED",
	LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
	LOGOUT_FAILED:"LOGOUT_FAILED",
	FETCH_LIST_SUCCESS:"FETCH_LIST_SUCCESS",
	FETCH_LIST_FAILED:"FETCH_LIST_FAILED",
	ADD_ITEM_SUCCESS:"ADD_ITEM_SUCCESS",
	ADD_ITEM_FAILED:"ADD_ITEM_FAILED",
	REMOVE_ITEM_SUCCESS:"REMOVE_ITEM_SUCCESS",
	REMOVE_ITEM_FAILED:"REMOVE_ITEM_FAILED",
	EDIT_ITEM_SUCCESS:"EDIT_ITEM_SUCCESS",
	EDIT_ITEM_FAILED:"EDIT_ITEM_FAILED"
}